### ISSUE TITLE
Need to check existence of directory/buffer

### ISSUE THREAD

**Issue by nyamada** [Boruch-Baum/emacs-crossword#1]
With a simple install of your file locally, M-x crossword results in two error messages -- 

1) local dir ~/Crosswords doesn't exist;

2) once I created the dir, and downloaded a puzzle, rerunning M-x crossword failed with the complaint that buffer "Crossword temporary" did not exist

**Comment by sarg** [comment]
I've managed to run it with `M-x crossword-download` and then `M-x crossword-load` the file.

**Comment by Boruch-Baum** [comment]
Looks fixed now. Sorry about that. Thanks for the feedback. Please verify that everything works with the new commit.
