### ISSUE TITLE
Title: Suggested Fix For Issue 9

### ISSUE THREAD

**Issue by tvraman** [Boruch-Baum/emacs-crossword#10]
Description: The present solution lives poorly with other packages
that also use advice, see previous issue #9.
A simple fix would be to declare the _n and _p args to the advicer
function as optional, this would also let you eliminate the need for
different advice-lambdas for emacs 27 vs 28 (given that you ignore the
args in both cases).
#

**Comment by Boruch-Baum** [comment]
Thank you. Your fix is correct per the emacs28 docstring for self-insert-command, so although I can't reproduce the issue in #9, I've applied a relevant patch in 474e330. Please verify that all is good now.
