### ISSUE TITLE
Error when trying to use the local crossword browser

### ISSUE THREAD

**Issue by maurooaranda** [Boruch-Baum/emacs-crossword#6]
Reproduced with Emacs 27.1 and Emacs 28.0.50
With emacs -Q and after loading crossword.el:

`M-x crossword RET Use the local crossword browser RET`

The command fails with the following message:

split-string: Args out of range: "\"Uh...\"--an uncomfortable pause.
Matt Jones

", 45, 44

It looks like the jz180531.puz file doesn't have the contents like
the code in crossword--summary-data-puz expects.

**Comment by maurooaranda** [comment]
If I add "Foo" between two null characters in jz180531.puz,
so that Publisher is Foo, the command succeeds.

**Comment by Boruch-Baum** [comment]
OK. I get it, but I can't reproduce it with my emacs26 or my emacs-snapshot from 2020-09. And to top things off, when I originally read the report, I thought "Uh... uncomfortable pause" was Jean-Louis' comment, not part of the response!

So, this is an issue you have with one particular sample puzzle. What is the md5sum of your original copy? ie. the one that caused the error.

When one of the three titile lines is missing, it should be a blank line, which is what I get.

**Comment by Boruch-Baum** [comment]
Reproduced! Give me a bit of time. I misunderstood your exact scenario originally

**Comment by Boruch-Baum** [comment]
I've just pushed a commit that solves the issue for me. Let me know. The commit just deletes three characters, so you may be tempted to just edit the file, but there have been other significant commits all day.

**Comment by maurooaranda** [comment]
> I've just pushed a commit that solves the issue for me. Let me know. The commit just deletes three characters, so you may be tempted to just edit the file, but there have been other significant commits all day.

Yes, I did a git pull and the problem is gone.

Thanks!

**Comment by Boruch-Baum** [comment]
I'll let Jean-Louis know.
